import {
  abhiman,
  aryan,
  aditya,
  akarsh,
  jatin,
  jatin2,
  satya,
  shivaji,
  simran,
  shree,
  res,
  vansh,
  karuna,
  loocina,
  reshma,
  gola,
  manas,
  nimit,
  swati,
  nitya,
  fashion,
  friend,
  soloSing,
  BoB,
  soloDance,
  groupDance,
  mono,
  nukkad,
  debate,
  interjection,
  poetry,
  murder,
  shortFilm,
  objectPromo,
  leaf,
  musicArt,
  exhibition,
  decathlon,
} from "./assets";

//?EVENTS DAY 1
export const d1events = [
  {
    id: "HBIe6hiOQJyBYOaH",
    name: "Fashion Walk",
    image: fashion,
    register: "https://forms.gle/2KCBvCR1TSE3djZ7A",
    desc: "",
    club: "",
  },
  {
    id: "eFvFEU6J5YpcS9Y1",
    name: "Find a Friend",
    image: friend,
    register: "https://forms.gle/MiMct1ou3kpMdkW4A",
    desc: "",
    club: "",
  },
  {
    id: "zNTLhQz4d9in37fi",
    name: "Solo Singing",
    image: soloSing,
    register: "https://forms.gle/jqc6bjRLQfyBDVXy7",
    desc: "Inter-College event showcasing singing talents from different colleges",
    club: "Moksha",
  },
  {
    id: "S9MjLmEtvJwZnjwr",
    name: "Battle of Bands",
    image: BoB,
    register: "https://forms.gle/uhjGrgoC8uaF3bDx5",
    desc: "Inter-College event showcasing bands from different colleges",
    club: "Moksha",
  },
  {
    id: "zrJh0QWvKL2n394i",
    name: "Solo/Duet Dance",
    image: soloDance,
    register: "https://forms.gle/NWsY6e1jkdCJC1cw7",
    desc: "Inter-College event where participants will perform either solo or as a duo, will be judged separately.",
    club: "Rage",
  },
  {
    id: "fpB9d0BgSIPLWp71",
    name: "Group Dance",
    image: groupDance,
    register: "https://forms.gle/qJNZcmfpePubvGVS6",
    desc: "Inter-College event where dance groups from different colleges will perform, will be judged as groups.",
    club: "Rage",
  },
  {
    id: "ZqQE5KDWEBDSYoiR",
    name: "Mono-act/Monologue",
    image: mono,
    register: "https://forms.gle/fQwWPS8ra3Eu7mRXA",
    desc: "Inter-college competition where students from different colleges will deliver speeches in the form of a play.",
    club: "Darpan",
  },
  {
    id: "pViet4VkFONm4m4O",
    name: "Nukkad Natak",
    image: nukkad,
    register: "https://forms.gle/MdmA12ra9AxgpoUB6",
    desc: "Street theater is a form of theatrical performance and presentation in outdoor public spaces. ",
    club: "Darpan",
  },
  {
    id: "Cy0gKCsUiDMxWuKV",
    name: "Conventional Debate",
    image: debate,
    register: "https://forms.gle/aHF55YV8aNZWfbx87",
    desc: "Conventional debate where students are provided with different topics to speak on, in the form of a competition.",
    club: "Confianza",
  },
  {
    id: "O5mwW0ybM4vOG3Aq",
    name: "Interjection",
    image: interjection,
    register: "https://forms.gle/aHF55YV8aNZWfbx87",
    desc: "Students will be given a topic to speak on, and will continue till another participant interjects due to either grammatical errors or factual fallacies. It is a competition.",
    club: "Confianza",
  },
];

//?EVENTS DAY 2
export const d2events = [
  {
    id: "toZm716kDuypQRh9",
    name: "Black out Poetry",
    image: poetry,
    register: "https://forms.gle/dCk3vbzvfuppd1MV8",
    desc: "A paragraph will be given to the participants out of which they have to pick certain words (by blacking out the rest of the words) to make a poem out of it.",
    club: "Atelier",
  },
  {
    id: "nWG0j9L8jRnEpJMq",
    name: "Murder Mystery",
    image: murder,
    register: "https://forms.gle/bZM6VoDpzNxDavPP9",
    desc: "Participants will have to solve a mystery with a set of given clues.",
    club: "Atelier",
  },
  {
    id: "vwjR2H76Ar7SvSab",
    name: "Short Film Making",
    image: shortFilm,
    register: "https://forms.gle/NJjYAeS6rorniS3DA",
    desc: "Film clubs of different colleges will be participating in this event. They will have to make a short film in the college campus itself, a general theme will be provided. Judges will be viewing the short films at the end of the day to declare the winner",
    club: "Film Odyssey",
  },
  {
    id: "wS79TjzAbL0Vxkk4",
    name: "Object Promo(Reel Making)",
    image: objectPromo,
    register: "https://forms.gle/5dCEpLRoEKLe91Hj6",
    desc: "Participation will be in pairs. They will have to make an advertisement for sponsors of this event.",
    club: "Film Odyssey",
  },
  {
    id: "mxxaNIZrHlTEcyJt",
    name: "Leaf Painting",
    image: leaf,
    register: "https://forms.gle/YhmL1gsc3fqvrtFQ7",
    desc: "Leaves will be provided to participants; they’ll have to draw on it.",
    club: "Akriti",
  },
  {
    id: "QZ347i2s6BigzVFW",
    name: "Music Art",
    image: musicArt,
    register: "https://forms.gle/H8fQGh8BUd5Bmxpy7",
    desc: "Participation will be in pairs. Both will be starting a sketch and when the music changes, they will exchange their sheets and continue each others’ drawing. Best pair will be picked at the end.",
    club: "Akriti",
  },
  {
    id: "vJ3KGR5XIJ4kYdE3",
    name: "Exhibition",
    image: exhibition,
    register: "https://forms.gle/8jJmzMRuRQAMMHYAA",
    desc: "Photography club and Fine Arts clubs will conduct an exhibition in association with each other. In this exhibition members of each club along with participants from other colleges will put up their Photographs/Artworks which will be judged by the audience by placing star shaped stickers on them.",
    club: "Clickerati",
  },
  {
    id: "NoOMzxdELNlUIU7b",
    name: "Decathlon",
    image: decathlon,
    register: "",
    desc: "",
    club: "",
  },
];

//*************TEAM */
export const teams = [
  {
    name: "Karuna Sharma",
    title: "President",
    image: karuna,
  },
  {
    name: "Satyabrata Kar",
    title: "Vice President",
    image: satya,
  },
  {
    name: "Restorjit Naorem",
    title: "Vice President",
    image: res,
  },
  {
    name: "Shivaji Pratap Singh",
    title: "Secretary",
    image: shivaji,
  },
  {
    name: "Aryan Rajput",
    title: "Joint Secretary",
    image: aryan,
  },
  {
    name: "Jatin Yadav",
    title: "Treasurer",
    image: jatin,
  },
  {
    name: "Nnimit Sharma",
    title: "Co Treasurer",
    image: nimit,
  },
  {
    name: "Akarshan Shahi",
    title: "Co Treasurer",
    image: akarsh,
  },
  {
    name: "Aditya Sinha",
    title: "Technical Head",
    image: aditya,
  },
  {
    name: "Vansh Bhardwaj",
    title: "Technical Co-Head",
    image: vansh,
  },
  {
    name: "Nithya Priya",
    title: "Graphics Head",
    image: nitya,
  },
  {
    name: "Simran Dhingra",
    title: "Graphics Co-Head",
    image: simran,
  },
  {
    name: "Swati Kumari",
    title: "PR Head",
    image: swati,
  },
  {
    name: "Jatin Khandodiya",
    title: "PR Co-Head",
    image: jatin2,
  },
  {
    name: "Srividya Rajgopal",
    title: "Event Coordinator",
    image: shree,
  },
  {
    name: "Abhimann Thakaran",
    title: "Event Coordinator",
    image: abhiman,
  },
  {
    name: "Loocina",
    title: "Event Coordinator",
    image: loocina,
  },
  {
    name: "K Reshma Rani",
    title: "Event Coordinator",
    image: reshma,
  },

  {
    name: "Manas Pratap Singh",
    title: "Event Coordinator",
    image: manas,
  },
];

//???******************SPONSORS
