import nobody from "./../assets/nobody.jpeg";
import {
  abhiman,
  aryan,
  aditya,
  akarsh,
  jatin,
  jatin2,
  satya,
  shivaji,
  simran,
  shree,
  res,
  vansh,
  karuna,
  loocina,
  reshma,
  manas,
  nimit,
  swati,
  nitya,
  thumbnail,
  avlokan,
  bands,
  fashion,
  karaoke,
  leaf,
  limelight,
  murder,
  nritya,
  pallate,
  poetry,
  solo,
  tarkshetra,
  zami,
} from "../assets";

//?EVENTS DAY 1
export const d1events = [
  {
    id: "leaf",
    name: "The Leafy Affair",
    image: leaf,
    register: "https://forms.gle/YhmL1gsc3fqvrtFQ7",
    desc: "Leaves will be provided to participants; they’ll have to draw on it.",
    club: "Akriti",
    timing: "10:00 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Room No. 19",
  },
  {
    id: "dance",
    name: "Nrityakala",
    image: nritya,
    register: "https://forms.gle/NWsY6e1jkdCJC1cw7",
    desc: "Inter-College event where participants will perform either solo or as a duo, will be judged separately.",
    club: "Rage",
    timing: "10:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Amphitheatre",
  },
  {
    id: "debate",
    name: "Tarkshetra",
    image: tarkshetra,
    register: "https://forms.gle/aHF55YV8aNZWfbx87",
    desc: "Conventional debate where students are provided with different topics to speak on, in the form of a competition.",
    club: "Confianza",
    timing: "11:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Room No 115",
  },
  {
    id: "mono",
    name: "Limelight",
    image: limelight,
    register: "https://forms.gle/fQwWPS8ra3Eu7mRXA",
    desc: "Inter-college competition where students from different colleges will deliver speeches in the form of a play.",
    club: "Darpan",
    timing: "11:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Basketball Court",
  },
  {
    id: "fashion",
    name: "Fashion Walk",
    image: fashion,
    register: "https://forms.gle/2KCBvCR1TSE3djZ7A",
    desc: "",
    club: "ECA",
    timing: "12:30 PM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Stage",
  },
  {
    id: "poetry",
    name: "Black out Poetry",
    image: poetry,
    register: "https://forms.gle/dCk3vbzvfuppd1MV8",
    desc: "A paragraph will be given to the participants out of which they have to pick certain words (by blacking out the rest of the words) to make a poem out of it.",
    club: "Atelier",
    timing: "1:30 PM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Room No. 19",
  },
  {
    id: "bands",
    name: "Battle of Bands",
    image: bands,
    register: "https://forms.gle/uhjGrgoC8uaF3bDx5",
    desc: "Inter-College event showcasing bands from different colleges",
    club: "Moksha",
    timing: "2:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Stage",
  },
  //?????DAY  1 ENDS*/
];

//?EVENTS DAY 2
export const d2events = [
  {
    id: "shortfilm",
    name: "Avlokan",
    image: avlokan,
    register: "https://forms.gle/NJjYAeS6rorniS3DA",
    desc: "Film clubs of different colleges will be participating in this event. They will have to make a short film in the college campus itself, a general theme will be provided. Judges will be viewing the short films at the end of the day to declare the winner",
    club: "Film Odyssey",
    timing: "10:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Room No. 22",
  },
  {
    id: "musicArt",
    name: "Music Pallate",
    image: pallate,
    register: "https://forms.gle/H8fQGh8BUd5Bmxpy7",
    desc: "Participation will be in pairs. Both will be starting a sketch and when the music changes, they will exchange their sheets and continue each others’ drawing. Best pair will be picked at the end.",
    club: "Akriti",
    timing: "10:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Badminton Court 2",
  },
  {
    id: "nukkad",
    name: "Zami Parasti",
    image: zami,
    register: "https://forms.gle/MdmA12ra9AxgpoUB6",
    desc: "Street theater is a form of theatrical performance and presentation in outdoor public spaces. ",
    club: "Darpan",
    timing: "11:00 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Haathi Park",
  },

  {
    id: "murder",
    name: "Who Done It ?",
    image: murder,
    register: "https://forms.gle/bZM6VoDpzNxDavPP9",
    desc: "Participants will have to solve a mystery with a set of given clues.",
    club: "Atelier",
    timing: "12:30 PM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Room No. 115",
  },

  {
    id: "singing",
    name: "Desh Ki Dhun",
    image: solo,
    register: "https://forms.gle/jqc6bjRLQfyBDVXy7",
    desc: "Inter-College event showcasing singing talents from different colleges",
    club: "Moksha",
    timing: "11:30 AM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Amphitheatre",
  },

  {
    id: "groupDance",
    name: "Group Dance",
    image: thumbnail,
    register: "https://forms.gle/qJNZcmfpePubvGVS6",
    desc: "Inter-College event where dance groups from different colleges will perform, will be judged as groups.",
    club: "Rage",
    timing: "2:00 PM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Stage",
  },
  {
    id: "friend",
    name: "Karaoke with Coffee",
    image: karaoke,
    register: "https://forms.gle/MiMct1ou3kpMdkW4A",
    desc: "",
    club: "ECA",
    timing: "3:00 PM",
    cord: "Abhimann Thakran",
    contact: "+91 8556654242",
    venue: "Near Coffee Shop , Football Ground",
  },
];

//*************TEAM */
export const teams = [
  {
    name: "Karuna Sharma",
    title: "President",
    image: karuna,
  },
  {
    name: "Satyabrata Kar",
    title: "Vice President",
    image: satya,
  },
  {
    name: "Restorjit Naorem",
    title: "Vice President",
    image: res,
  },
  {
    name: "Shivaji Pratap Singh",
    title: "Secretary",
    image: shivaji,
  },
  {
    name: "Aryan Rajput",
    title: "Joint Secretary",
    image: aryan,
  },
  {
    name: "Jatin Yadav",
    title: "Treasurer",
    image: jatin,
  },
  {
    name: "Nnimit Sharma",
    title: "Co Treasurer",
    image: nimit,
  },
  {
    name: "Akarshan Shahi",
    title: "Co Treasurer",
    image: akarsh,
  },
  {
    name: "Aditya Sinha",
    title: "Technical Head",
    image: aditya,
  },
  {
    name: "Vansh Bhardwaj",
    title: "Technical Co-Head",
    image: vansh,
  },
  {
    name: "Nithya Priya",
    title: "Graphics Head",
    image: nitya,
  },
  {
    name: "Simran Dhingra",
    title: "Graphics Co-Head",
    image: simran,
  },
  {
    name: "Swati Kumari",
    title: "PR Head",
    image: swati,
  },
  {
    name: "Jatin Khandodiya",
    title: "PR Co-Head",
    image: jatin2,
  },
  {
    name: "Srividya Rajgopal",
    title: "Event Coordinator",
    image: shree,
  },
  {
    name: "Abhimann Thakaran",
    title: "Event Coordinator",
    image: abhiman,
  },
  {
    name: "Loocina",
    title: "Event Coordinator",
    image: loocina,
  },
  {
    name: "K Reshma Rani",
    title: "Event Coordinator",
    image: reshma,
  },

  {
    name: "Manas Pratap Singh",
    title: "Event Coordinator",
    image: manas,
  },
];

//???******************SPONSORS
export const sponsors = [
  { name: "koi nhi h  :)", image: nobody, class: "" },
  { name: "koi nhi h  :)", image: nobody, class: "animate__delay-1s" },
  { name: "koi nhi h  :)", image: nobody, class: "animate__delay-2s" },
  { name: "koi nhi h  :)", image: nobody, class: "animate__delay-3s" },
  { name: "koi nhi h a:)", image: nobody, class: "animate__delay-4s" },
  { name: "koi nhi h a:)", image: nobody, class: "animate__delay-5s" },
];
